apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: l8z1qichn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l8z1qichn-python 
  name: l8z1qichn-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: l8z1qichn-python
    weight: 100 
